# HMS Networks Solution Center
# Make Branch Action for Maven-based Ewon ETK Project Releases
# Version: 1.0
#
# This action is configured to automatically run when a release
# tag is created in the following syntax: `v*`.

name: Release (Make Branch)

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Create Release Branch
    runs-on: ubuntu-latest
    steps:

      - name: Branch name # Build a branch name from tag (vX.Y) in release/X.Y format
        id: branch_name
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          tagRevision="${tag:1}"
          branchPrefix="release/"
          branchName="$branchPrefix$tagRevision"
          echo ::set-output name=SOURCE_TAG::"$branchName"

      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        with:
          branch: ${{ steps.branch_name.outputs.SOURCE_TAG }}